"""
Monthly "CIO Research Review" (Phase 5) -- an advisory-only report
comparing strategies' research evidence, evidence quality, and live
paper-trading performance, ending in ONE recommendation from a fixed
enumerated list. Named "CIO Research Review" only as report-facing
business language, per explicit direction -- the module itself is named
lifecycle_review.py specifically to avoid any file-path overlap with the
real cio/chief_investment_ai.py.

*** THIS MODULE IS COMPLETELY SEPARATE FROM, AND NEVER IMPORTS OR CALLS,
THE REAL cio/ PACKAGE. *** cio/chief_investment_ai.py is a real, live,
monthly-cadence capital-allocation engine that already runs and already
writes data/monthly_plan.json, constraining real production capital and
strategy selection every day. This module has ZERO connection to that --
it never imports cio/, never reads or writes data/monthly_plan.json,
never touches execution/, and its output is a plain markdown file with an
explicit disclaimer, never fed back into any production decision path.

GOVERNANCE (explicit, 2026-08-04): this review ONLY MAKES A
RECOMMENDATION. It never calls deployment_manager.set_deployment_status()
or anything else that would apply its own recommendation automatically.
A human reads the recommendation and, separately, decides.
"""

import os
from datetime import datetime
from typing import Callable, Optional

from deployment.base import DeploymentStatus
from deployment.deployment_manager import list_strategies
from deployment.drift_report import load_drift_history
from deployment.paper_trading_engine import compute_live_metrics, load_portfolio
from deployment.settings import LIFECYCLE_REVIEWS_DIR

DISCLAIMER = (
    "**DISCLAIMER: This is an advisory-only research review, generated by the isolated Research "
    "Deployment system (deployment/lifecycle_review.py). It has NO connection to, and never "
    "reads from or writes to, the production cio/chief_investment_ai.py module or "
    "data/monthly_plan.json. It makes ZERO automatic changes to production capital allocation, "
    "strategy selection, or deployment status. Every recommendation below requires a separate, "
    "explicit human decision to act on.**"
)

RECOMMENDATIONS = (
    "Continue Paper Trading", "Extend Paper Trading", "Promote to Pilot Live Allocation",
    "Keep Existing Production Allocation Unchanged", "Reduce Future Allocation",
    "Increase Future Allocation", "Archive Strategy",
)


def _gather_strategy_facts(strategy_key: str, record) -> dict:
    facts = {
        "display_name": record.display_name, "strategy_id": record.strategy_id,
        "research_verdict": record.research_verdict.value,
        "research_verdict_source": record.research_verdict_source,
        "deployment_status": record.deployment_status.value,
    }
    if record.deployment_status in (DeploymentStatus.PAPER_TRADING, DeploymentStatus.PILOT_LIVE,
                                     DeploymentStatus.PRODUCTION):
        portfolio = load_portfolio(strategy_key)
        if portfolio.get("last_processed_date"):
            facts["live_metrics"] = compute_live_metrics(strategy_key)
            facts["last_processed_date"] = portfolio["last_processed_date"]

    drift_history = load_drift_history(strategy_key)
    if drift_history:
        facts["latest_drift"] = drift_history[-1]   # most recent snapshot only -- see load_drift_history()
    return facts


def build_review_prompt(strategy_facts: list) -> str:
    sections = []
    for facts in strategy_facts:
        lines = [f"### {facts['display_name']} ({facts.get('strategy_id') or 'no id'})",
                 f"Research Verdict: {facts['research_verdict']} (source: {facts.get('research_verdict_source') or 'n/a'})",
                 f"Deployment Status: {facts['deployment_status']}"]
        if "live_metrics" in facts:
            m = facts["live_metrics"]
            lines.append(f"Live paper-trading (as of {facts['last_processed_date']}): "
                         f"trades={m['total_trades']} win_rate={m['win_rate']} "
                         f"expectancy={m['expectancy']} CAGR={m.get('cagr')}% "
                         f"Sharpe={m.get('sharpe_ratio')} MaxDD={m.get('max_drawdown_pct')}%")
        if "latest_drift" in facts:
            drift = facts["latest_drift"]
            flags = drift.get("flags") or {}
            lines.append(f"Latest live-vs-historical drift snapshot ({drift['generated_at']}, "
                         f"vs {drift['historical_exp_id']}): "
                         f"{'MATERIAL DRIFT on: ' + ', '.join(flags.keys()) if flags else 'no material drift flagged'}")
        sections.append("\n".join(lines))
    joined = "\n\n".join(sections)

    return f"""You are producing an advisory-only monthly research review comparing the strategies below. \
This review has NO connection to any production capital-allocation system -- it is purely advisory research \
output for a human decision-maker.

{joined}

For EACH strategy, using ONLY the objective facts above (do not invent numbers), briefly discuss:
1. Historical research evidence and its quality.
2. Live paper-trading performance, if any exists yet, and whether it looks consistent with the historical
   research evidence.
3. Any live-vs-historical drift flagged above, and what it might mean.
4. Risk considerations.

Then, for EACH strategy, give exactly ONE recommendation chosen from this fixed list (use the exact wording):
{", ".join(RECOMMENDATIONS)}.

Do not recommend any action outside this list. Do not claim this review changes anything automatically --
every recommendation requires a separate human decision."""


def generate_monthly_review(call_fn: Optional[Callable[[str], str]] = None, api_key: str = "",
                             registry_path=None, output_dir: str = LIFECYCLE_REVIEWS_DIR) -> str:
    kwargs = {"registry_path": registry_path} if registry_path else {}
    records = list_strategies(**kwargs)
    strategy_facts = [_gather_strategy_facts(r.strategy_key, r) for r in records]

    prompt = build_review_prompt(strategy_facts)

    if call_fn is not None:
        call = call_fn
    else:
        from news.news_agent import call_claude
        call = lambda p: call_claude(p, api_key, max_tokens=4096)

    review_text = call(prompt)

    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    path = os.path.join(output_dir, f"{timestamp}_cio_research_review.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# CIO Research Review\n\n{DISCLAIMER}\n\nGenerated: {timestamp}\n\n---\n\n{review_text}")
    return path
